language: node_js
node_js:
  - "9.4"
after_script:
  - npm run-script test
notifications:
  slack:
    rooms:
      redpelicans:xCuMR4Ld1A0cSDdgpgYtJvrW#schooljs
      redpelicans:xCuMR4Ld1A0cSDdgpgYtJvrW#ci
