language: node_js
node_js:
  - "9.4"
script:
  - "yarn test --coverage"
notifications:
  slack:
    rooms:
      redpelicans:xCuMR4Ld1A0cSDdgpgYtJvrW#schooljs
      redpelicans:xCuMR4Ld1A0cSDdgpgYtJvrW#ci
after_script:
  - "npm install -g coveralls && cat coverage/lcov.info | coveralls" 
